[metadata]
format.version = "1.1"

[versions]
edc = "0.14.1"
shadow = "9.3.1"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.27.6" }
jakarta-json = { module = "org.glassfish:jakarta.json", version = "2.0.1" }
jakarta-json-api = { module = "jakarta.json:jakarta.json-api", version = "2.1.3" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.20.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
parsson = { module = "org.eclipse.parsson:parsson", version = "1.1.7" }
testcontainers = { module = "org.testcontainers:junit-jupiter", version = "1.21.4" }
titanium-json-ld = { module = "com.apicatalog:titanium-json-ld", version = "1.7.0" }

edc-controlplane-base-bom = { module = "org.eclipse.edc:controlplane-base-bom", version.ref = "edc" }
edc-crawler-spi = { module = "org.eclipse.edc:crawler-spi", version.ref = "edc" }
edc-dataplane-base-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-federatedcatalog-bom = { module = "org.eclipse.edc:federatedcatalog-base-bom", version.ref = "edc" }
edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
