[metadata]
format.version = "1.1"

[versions]

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.27.6" }
jakarta-json = { module = "org.glassfish:jakarta.json", version = "2.0.1" }
jakarta-json-api = { module = "jakarta.json:jakarta.json-api", version = "2.1.3" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.20.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
parsson = { module = "org.eclipse.parsson:parsson", version = "1.1.7" }
testcontainers = { module = "org.testcontainers:junit-jupiter", version = "1.21.3" }
titanium-json-ld = { module = "com.apicatalog:titanium-json-ld", version = "1.7.0" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
